name: rocketshp
channels:
  - conda-forge
  - pytorch
  - nvidia
  - bioconda
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pytorch
  - pytorch-cuda=12.4
  - biopython
  - transformers
  - h5py
  - torchmd-net
  - rdkit
  - wandb
  - foldseek
  - pip:
    - python-dotenv
    - -e .
    - nglview
    - ipymolstar
    - mdtraj