autocorr_alpha: 0.0
batch_size: 8
ca_dist_alpha: 1.0
crop_size: 512
d_model: 768
dyn_corr_alpha: 0.0
embedding_dim: 1536
epoch_scale: -1
gcc_lmi_alpha: 1.0
grad_norm: false
lr: 0.0001778279410038923
max_epochs: 75
n_heads: 12
n_layers: 12
num_data_workers: 31
output_dim: 1
precision: medium
random_seed: 0
rmsf_alpha: 1.0
seq_features: true
shp_alpha: 0.01
shuffle: true
square_loss: false
struct_dim: 1024
struct_features: true
struct_stage: encoded
train_pct: 0.8
val_pct: 0.1
variance_norm: false
