random_seed: 0

# Data definitions
num_data_workers: 31
crop_size: 512
shuffle: True
train_pct: 0.8
val_pct: 0.1

# Model definitions
embedding_dim: 1536
output_dim: 1
d_model: 768
n_heads: 12
n_layers: 12
seq_features: true
struct_features: true
struct_stage: "encoded"
struct_dim: 1024

# Training definitions
batch_size: 8
lr: 0.0001
max_epochs: 75
epoch_scale: -1
precision: "medium"
square_loss: false
variance_norm: false
grad_norm: false

# Targets
rmsf_alpha: 1.0
ca_dist_alpha: 0.5
gcc_lmi_alpha: 1.0
shp_alpha: 0.01