batch_size: 16
ca_dist_alpha: 1.0
d_model: 768
description: Basic hyperparameter optimization for RocketSHP
gcc_lmi_alpha: 1.0
lr: 0.0001778279410038923
metric:
  direction: minimize
  name: final/val_loss
n_heads: 6
n_layers: 12
name: rocketshp_basic_sweep
parameters:
  batch_size:
    type: categorical
    values:
    - 8
    - 16
    - 32
  lr:
    max: 0.001
    min: 1.0e-06
    scale: log
    type: double
  model_config:
    type: categorical
    values:
    - d_model: 256
      n_heads: 4
    - d_model: 256
      n_heads: 8
    - d_model: 512
      n_heads: 4
    - d_model: 512
      n_heads: 8
    - d_model: 512
      n_heads: 16
    - d_model: 768
      n_heads: 6
    - d_model: 768
      n_heads: 8
    - d_model: 768
      n_heads: 12
    - d_model: 1024
      n_heads: 8
    - d_model: 1024
      n_heads: 16
  n_layers:
    type: categorical
    values:
    - 6
    - 8
    - 10
    - 12
project: samsl-flatiron/RocketSHP
rmsf_alpha: 1.0
shp_alpha: 0.01
strategy:
  type: grid
