batch_size: 8
ca_dist_alpha: 0.48785054702257036
d_model: 768
description: Loss weight optimization for RocketSHP
gcc_lmi_alpha: 1.0177422790959092
lr: 0.0001778279410038923
metric:
  direction: minimize
  name: final/val_loss
n_heads: 12
n_layers: 12
name: rocketshp_loss_weights_sweep
parameters:
  ca_dist_alpha:
    max: 2.0
    min: 0.1
    type: double
  gcc_lmi_alpha:
    max: 2.0
    min: 0.1
    type: double
  rmsf_alpha:
    max: 2.0
    min: 0.1
    type: double
  shp_alpha:
    max: 0.1
    min: 0.001
    type: double
project: samsl-flatiron/RocketSHP
rmsf_alpha: 1.998398546694881
shp_alpha: 0.009630088841667751
strategy:
  type: random
