project: "samsl-flatiron/RocketSHP"
name: "rocketshp_loss_weights_sweep"
description: "Loss weight optimization for RocketSHP"

parameters:
  rmsf_alpha:
    type: "double"
    min: 0.1
    max: 2.0
  
  ca_dist_alpha:
    type: "double"
    min: 0.1
    max: 2.0
  
  gcc_lmi_alpha:
    type: "double"
    min: 0.1
    max: 2.0
  
  shp_alpha:
    type: "double"
    min: 0.001
    max: 0.1

strategy:
  type: "random"
  
metric:
  name: "final/val_loss"
  direction: "minimize"